### ISSUE TITLE
我安装 npm install react-router-dom --save 这个模块 直接安装不了？

### ISSUE THREAD

**Issue by naihe138** [qiqiboy/tiger-new#2]
我安装 npm install react-router-dom --save 这个模块 直接安装不了？报错如下

````
npm ERR! path /Users/naihe/.npm/_logs/2017-06-18T08_51_31_392Z-debug.log
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/Users/naihe/.npm/_logs/2017-06-18T08_51_31_392Z-debug.log'
npm ERR!     at Object.fs.unlinkSync (fs.js:1066:18)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:305:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:319:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at Glob.emit (events.js:210:7)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:149:14)
npm ERR!  { Error: EACCES: permission denied, unlink '/Users/naihe/.npm/_logs/2017-06-18T08_51_31_392Z-debug.log'
npm ERR!     at Object.fs.unlinkSync (fs.js:1066:18)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:305:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:319:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at emitOne (events.js:115:13)
npm ERR!     at Glob.emit (events.js:210:7)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:31:16)
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob._readdirEntries (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:578:10)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:555:12
npm ERR!     at go$readdir$cb (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:149:14)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/Users/naihe/.npm/_logs/2017-06-18T08_51_31_392Z-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Maximum call stack size exceeded
````

npm v5.0.3
node v8.1.2

求大神解答

**Comment by qiqiboy** [comment]
把项目下的node_modules目录全删了，再重新安装试试。
